import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Layout from '../components/Layout';
import utilStyle from '../styles/utils.module.css';
import { getPostsData } from "@/lib/post";

// SSG の場合 
export async function getStaticProps() {
  const allPostsData = getPostsData(); // id, title, date, thumbnail
  console.log("allPostsData", allPostsData);

  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({ allPostsData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout home>
        <section className={utilStyle.headingMd}>
          <p className={utilStyle.leftStart}>
            プログラミング学習中 ! プログラミングスクールRUNTEQで Ruby on Rails を中心に学習。
            現在は React、Next.js を学習しながら就活中。
          </p>
          <p className={utilStyle.leftStart}>
            RUNTEQ技術サポーター。
          </p>
          <h4>📝ブログ</h4>
        </section>

        <div className={styles.grid}>
          {allPostsData.map(({id, title, date, thumbnail}) => (
            <article key={id}>
              <Link href={`/posts/${id}`}>
                <img
                  src={`${thumbnail}`}
                  className={styles.thumbnailImage} />
              </Link>
              <Link href={`/posts/${id}`}>
                <span className={utilStyle.boldText}>
                  {title}
                </span>
              </Link>
                <br />
                <small className={utilStyle.lightText}>{date}</small>
            </article>
          ))}
        
        </div>
      </Layout>
    </>
  );
}
